package com.blogspot.fravalle.lib.importer.bookmarks;

public enum EBookmarkStatus {

    ONLINE, NOT_FOUND, POTENTIAL_NOT_FOUND, IOEXCEPTION, MALFORMEDURLEXCEPTION, CONN_CLASSCASTEXCEPTION, UNKNOWNSERVICEEXCEPTION, SSLHANDSHAKEEXCEPTION, CONN_EXCEPTION, STRANGE_FILENOTFOUND_CONN_EXCEPTION, NOT_MORE_REACHABLE

}
