/*
 * SideBar.java - jdocman (jdocman.jar)
 * Copyright (C) 2003
 * Source file created on 14-nov-2003
 * Author: Francesco Valle <info@weev.it>
 * http://www.weev.it
 *
 */

package com.blogspot.fravalle.lib.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

import com.blogspot.fravalle.lib.monitor.Monitor;
import com.blogspot.fravalle.util.Constants;


/**
 * @author antares
 *
 */
public class SideBar extends JPanel {
	
	private String[][] tabLabels;
	private int tabWidth;
	private int tabHeight;

	private int oldCompId = -1;
	private int newCompId = -1;
	private int lstCompId = -1;
	
	
	public void addObj(JToggleButton jcomp, int tabIdx) {

		((JPanel)jpWest.getComponent(tabIdx)).add(jcomp);
		((JPanel)jpWest.getComponent(tabIdx)).updateUI();

	}

	private void toggleBar(java.awt.event.ActionEvent evt, int idx, int oldIdx) {
		lstCompId = idx;
		if ( ((JToggleButton)evt.getSource()).isSelected() ) {
			
			((JToggleButton)(((Component)evt.getSource()).getParent()).getComponent(oldIdx-1)).setSelected(false);
			
			// java.awt.GridBagConstraints gridBagConstraints1 = ((GridBagLayout)jpWest.getLayout()).getConstraints( (Component)evt.getSource() );
			java.awt.GridBagConstraints gridBagConstraints1 = ((GridBagLayout)jpWest.getLayout()).getConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(idx)
					);
			java.awt.GridBagConstraints gridBagConstraintsOld = ((GridBagLayout)jpWest.getLayout()).getConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(oldIdx)
					);
			
			
			gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
			gridBagConstraints1.weighty = 1.0;
			gridBagConstraintsOld.fill = java.awt.GridBagConstraints.BOTH;
			gridBagConstraintsOld.weighty = 0.0;
			
			
			((GridBagLayout)jpWest.getLayout()).setConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(idx)
					, gridBagConstraints1 );
			((GridBagLayout)jpWest.getLayout()).setConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(oldIdx)
					, gridBagConstraintsOld );
		} else {
		    
			((JToggleButton)(((Component)evt.getSource()).getParent()).getComponent(oldIdx-1)).setSelected(true);
		    
			java.awt.GridBagConstraints gridBagConstraints1 = ((GridBagLayout)jpWest.getLayout()).getConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(idx)
					);
			java.awt.GridBagConstraints gridBagConstraintsOld = ((GridBagLayout)jpWest.getLayout()).getConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(oldIdx)
					);
			
			
			gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
			gridBagConstraints1.weighty = 0.0;
			gridBagConstraintsOld.fill = java.awt.GridBagConstraints.BOTH;
			gridBagConstraintsOld.weighty = 1.0;
			
			
			((GridBagLayout)jpWest.getLayout()).setConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(idx)
					, gridBagConstraints1 );
			((GridBagLayout)jpWest.getLayout()).setConstraints(
					(((Component)evt.getSource()).getParent()).getComponent(oldIdx)
					, gridBagConstraintsOld );
			
		}
		jpWest.updateUI();
	}

	public SideBar(String[][] tabLabels, int tabWidth, int tabHeight) {
		this.tabLabels = tabLabels;
		this.tabWidth = tabWidth;
		this.tabHeight = tabHeight;
		initComponents();
	}
	
	public SideBar(String[][] tabLabels) {
	    /*
	     new String[][] {
								   {"Aria","/res/img/archive"},
								   {"Acqua","/res/img/lib"},
								   {"Fuoco","/res/img/email-x"},
								   {"Terra","/res/img/home-x"}
	     }
	    */
		this.tabLabels = tabLabels;
		this.tabWidth = 150;
		this.tabHeight = 20;
		initComponents();
	}
	

	/* BEGIN F4J GUI CODE */
	
	/** Creates new form JNMan */
	public SideBar() {}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
		jpWest = new javax.swing.JPanel();
		
		setLayout(new java.awt.BorderLayout());
		jpWest.setLayout(new java.awt.GridBagLayout());
		
		int total = tabLabels.length;
		for (int i=0,e=0; i < total; i++) {
			javax.swing.JToggleButton jToggleButton1 = new javax.swing.JToggleButton();
			javax.swing.JPanel jPanel12 = new javax.swing.JPanel();
			java.awt.GridBagConstraints gridBagConstraints1 = new java.awt.GridBagConstraints();
			
			jToggleButton1.setText( tabLabels[i][0] );
			
			Monitor.log( Constants._logDefaultDef + "ROW-AFTER:" + e);
			if (tabLabels[i][1] != null) {
			    String imageBaseName = tabLabels[i][1];
			    String suffix = "";
			    if (imageBaseName == "") {
			        imageBaseName = "/res/img/archive";
			    } else {
			        if (imageBaseName.endsWith("-x")) suffix = "";
			        else  suffix = "-open";
			    }

				ImageIcon imageIcon = new ImageIcon( getClass().getResource( imageBaseName + ".gif" ) );
				ImageIcon open_imageIcon = new ImageIcon( getClass().getResource( imageBaseName + suffix + ".gif" ) );
				
				tabHeight = imageIcon.getIconHeight()+6;
				jToggleButton1.setIcon(imageIcon);
				jToggleButton1.setRolloverSelectedIcon( imageIcon );
				jToggleButton1.setRolloverIcon( open_imageIcon );
				jToggleButton1.setSelectedIcon( open_imageIcon );
			}
			
			jToggleButton1.setPreferredSize( new Dimension( tabWidth, tabHeight ) );
		
			
			gridBagConstraints1.gridx = 0;
			gridBagConstraints1.gridy = e++;
			gridBagConstraints1.fill = java.awt.GridBagConstraints.VERTICAL;
			
			final int trasferId = e;
			jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
				public void actionPerformed(java.awt.event.ActionEvent evt) {
					jToggleButton1ActionPerformed(evt, trasferId);
				}
			});			
			
			jpWest.add(jToggleButton1, gridBagConstraints1);
			
			
			jPanel12.setBackground(new java.awt.Color(204, 255, 204));
			jPanel12.setMaximumSize(new java.awt.Dimension(tabWidth, 0));
			jPanel12.setMinimumSize(new java.awt.Dimension(tabWidth, 0));
			jPanel12.setPreferredSize(new java.awt.Dimension(tabWidth, 0));
			gridBagConstraints1 = new java.awt.GridBagConstraints();
			gridBagConstraints1.gridx = 0;
			gridBagConstraints1.gridy = e++;
			gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
			if (i==total-1) gridBagConstraints1.weighty = 1.0;
			jpWest.add(jPanel12, gridBagConstraints1);
			
			
		}
		
		add(jpWest, java.awt.BorderLayout.WEST);
		
		
		/*
		javax.swing.JToggleButton jToggleButton1 = new javax.swing.JToggleButton();
		javax.swing.JPanel jPanel12 = new javax.swing.JPanel();
		javax.swing.JToggleButton jToggleButton2 = new javax.swing.JToggleButton();
		javax.swing.JPanel jPanel13 = new javax.swing.JPanel();

		java.awt.GridBagConstraints gridBagConstraints1;
        
		jToggleButton1.setText("A");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});
        
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.VERTICAL;
		jpWest.add(jToggleButton1, gridBagConstraints1);
        
		jPanel12.setBackground(new java.awt.Color(204, 255, 204));
		jPanel12.setMaximumSize(new java.awt.Dimension(1, 1));
		jPanel12.setMinimumSize(new java.awt.Dimension(1, 1));
		jPanel12.setPreferredSize(new java.awt.Dimension(1, 1));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		jpWest.add(jPanel12, gridBagConstraints1);
        
		jToggleButton2.setText("B");
		jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton2ActionPerformed(evt);
			}
		});
        
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 2;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.VERTICAL;
		jpWest.add(jToggleButton2, gridBagConstraints1);
        
		jPanel13.setBackground(new java.awt.Color(255, 255, 153));
		jPanel13.setMaximumSize(new java.awt.Dimension(1, 1));
		jPanel13.setMinimumSize(new java.awt.Dimension(1, 1));
		jPanel13.setPreferredSize(new java.awt.Dimension(1, 1));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 3;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.weighty = 1.0;
		jpWest.add(jPanel13, gridBagConstraints1);
        
		add(jpWest, java.awt.BorderLayout.WEST);
        */
		
		
	}

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt, int compId) {
		int totalElements = (((Component)evt.getSource()).getParent()).getComponentCount();
		newCompId = compId;
		if (oldCompId == -1) oldCompId = totalElements-1;
		else oldCompId = lstCompId;
		toggleBar(evt, compId, oldCompId);
	}



	// Variables declaration - do not modify
	private javax.swing.JPanel jpWest;
	/*
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JToggleButton jToggleButton2;
	private javax.swing.JPanel jPanel13;
	*/
	// End of variables declaration

}
